image: node:10.15.3

services:
  - postgres:latest

variables:
  PGDATABASE: nice_marmot
  PGUSER: runner

cache:
  paths:
  - node_modules/

stages:
  - test

test_all:
  stage: test
  script:
   - cd data-api
   - npm install
   - npm test
  tags:
    - docker